### ISSUE TITLE
Why we need to resize from 384x384 to 192x192

### ISSUE THREAD

**Issue by dong274** [SorourMo/38-Cloud-A-Cloud-Segmentation-Dataset#1]
Hi, thank you for great works. 
I have a question. In your paper. you cropped 8000x8000 image into 384x384 patches and then resize them into 192x192. Why you did not directly crop image into 192x192 patches, it confused me. Thank in advance

**Comment by SorourMo** [comment]
Hi,
Thank you for your question. It has two reasons basically:
1- The size of the feature maps in the contracting part of the network decreases from 192x192 in the input layer to 6x6 at the bridge of the network. Based on our empirical experiences, if we chose the input size anything greater than 192x192, we would not end up with a small feature map size of 6x6  at the bridge anymore and, as a result, the performance of the system would decrease. This means that the best performance occurs with an input size of 192x192.
2- We have noticed that sometimes as the "number" of patches covering a complete image increases, the artifacts corresponding to the boundaries of the predicted cloud mask of each patch ruin the generated complete mask. It is like some checkerboard artifacts appear in a complete mask. So we needed to keep the number of patches covering a complete image as low as possible. This means the size of each patch should be greater than the default size 192x192. Based on the reason mentioned in "1", we simply cropped complete images into 384*384 but resized them before being fed to the network to get the most out of the network field of view.

**Comment by joey1314** [comment]
Hi Sorour. So if we resize the input size to 192 (training or test),  some important or interested information may be losed, then the trained model may have some trouble in applying. However, when i used the model to predict the test dataset you released, the results were amazing , actually only 0.2 lower than the 384 input during test. Therefore i am so confused. Hope for your help, and thank you in advance.
