### ISSUE TITLE
HI,where can i download the detail's of you model?

### ISSUE THREAD

**Issue by LYTXJY** [SorourMo/38-Cloud-A-Cloud-Segmentation-Dataset#2]

**Comment by LYTXJY** [comment]
just like 'Cloud-Net',i could not find anything in github

**Comment by SorourMo** [comment]
Thank you for your interest. unfortunately, the Cloud-Net model has not been released yet here. It will be available in the future.

**Comment by SorourMo** [comment]
Hello,

The Cloud-Net codes and weights have been uploaded here:
https://github.com/SorourMo/Cloud-Net-A-semantic-segmentation-CNN-for-cloud-detection
