### ISSUE TITLE
Unable to download the dataset

### ISSUE THREAD

**Issue by frodofights** [SorourMo/38-Cloud-A-Cloud-Segmentation-Dataset#4]
Hi!

Whenever I start download, it continues for sometime and then fails. The behaviour is same when I download from work or home. 
Would it be possible for you to upload it somewhere else, like google drive or some other cloud service?

Thanks!

**Comment by SorourMo** [comment]
Hi there,
Sorry to hear that. Have you tried downloading training and test sets separately via two provided [links](https://github.com/SorourMo/38-Cloud-A-Cloud-Segmentation-Dataset#click-here-for-downloading-the-test-set-separately)?

Please let me know if you still have a problem.

**Comment by SorourMo** [comment]
I have uploaded the dataset at Kaggle as well:
https://www.kaggle.com/sorour/38cloud-cloud-segmentation-in-satellite-images/download
