### ISSUE TITLE
Entire predicted scene

### ISSUE THREAD

**Issue by joey1314** [SorourMo/38-Cloud-A-Cloud-Segmentation-Dataset#5]
Hi, Sorour.
you said in your readme that the output of the mfile are an excel and a text file, and so how can we get the **Entire Predicted Scenes image**. When i run the mfile , it always tell me that the function can not be defined in the context, so i think it maybe the version of the Matlab does not match? So please tell me your Matlab version, thank you.

such as,
function out = QE_calcul (predict,gt, labels, conf_print)
    out_both = cfmatrix(gt(:), predict(:), labels, 1, conf_print);
    
    % We are interested in getting the numerical evaluators of "1" or
    % "cloud" class only
    ix = find(labels(:)==1);
    out = out_both (ix,:); 
end

AND THE ERROR IS，
Error: File: evaluation.m Line: 1 Column: 1
Function definitions are not allowed in this context

**Comment by SorourMo** [comment]
The entire predicted mask is automatically saved in a newly created directory starting with 'entire_masks_'.
The code has been tested with Matlab version 2018b.

**Comment by joey1314** [comment]
ok, thank you. And i have get the results with matlab 2016b. Due to the Nvidia gpu memory，i have set the size to 192*192, and the runtime is around 4 minutes, what amazes me is that even if the input size is 192*192 , the evaluation resluts are so beautiful.
Precision, Recall, Specificity, Jaccard, Overall Accuracy
89.841304, 84.939363, 98.288317, 77.656635, 96.291394
only a litttle lower than the sample results you release.

At 2019-09-02 01:06:14, "Sorour Mohajerani" <notifications@github.com> wrote:


The entire predicted mask is automatically saved in a newly created directory starting with 'entire_masks_'.
The code has been tested with Matlab version 2018b.

**Comment by SorourMo** [comment]
Sounds good!
