### ISSUE TITLE
Why  are the two evaluation indicators very different

### ISSUE THREAD

**Issue by Silengcewang** [SorourMo/38-Cloud-A-Cloud-Segmentation-Dataset#7]
Sorry to disturb U , but i have a question that why the evaluatiion indicators in the "Cloud-net" and "Cloud_net++" are different. and could u share me the codes?

**Comment by SorourMo** [comment]
Hi.
The evaluation metrics described in Cloud-net are calculated first over **each test image**. Then they are averaged over the total number of test images. Like this: 
Jaccard of the first test image: Jaccard1 = tp1/(tp1+fp1+fn1)
Jaccard of the second test image: Jaccard2 = tp2/(tp2+fp2+fn2)
.
.
Total Jaccard = (Jaccard1+Jaccard2+...+JaccardM)/M
where M is the total num of images.
In Cloud-net+, tp, fp, fn, and tn are measured for **each target class** and then metrics are calculated as mentioned in the "evaluation metrics" section of the paper. Like this:
Total Jaccard = (tp1 + tp2+ ... + tpM)/((tp1 + tp2+ ... + tpM)+(fp1 + fp2+ ... + fpM)+(fn1 + fn2+ ... + fnM))
That is the same for other metrics too.
Cloud-Net+ code will be available soon.

**Comment by Silengcewang** [comment]
Thank you for your reply.
Because that we usually use the first evaluatuion metrics and the second one seems have a better performance.So i'm very confused.Whatever thank&nbsp; you for your reply again and i will try the to metrics to find the difference.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SorourMo/38-Cloud-A-Cloud-Segmentation-Dataset"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月30日(星期一) 凌晨0:02
收件人:&nbsp;"SorourMo/38-Cloud-A-Cloud-Segmentation-Dataset"<38-Cloud-A-Cloud-Segmentation-Dataset@noreply.github.com&gt;;
抄送:&nbsp;"鼬手边是佐手"<799510953@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SorourMo/38-Cloud-A-Cloud-Segmentation-Dataset] Why  are the two evaluation indicators very different (#7)





 
Hi.
 The evaluation metrics described in Cloud-net are calculated first over each test image. Then they are averaged over the total number of test images. Like this:
 Jaccard of the first test image: Jaccard1 = tp1/(tp1+fp1+fn1)
 Jaccard of the second test image: Jaccard2 = tp2/(tp2+fp2+fn2)
 .
 .
 Total Jaccard = (Jaccard1+Jaccard2+...)/M
 where M is the total num of images.
 In Cloud-net+, tp, fp, fn, and tn are measured for each target class and then metrics are calculated as mentioned in the "evaluation metrics" section of the paper. Like this:
 Total Jaccard = (tp1 + tp2+ ... + tpM)/((tp1 + tp2+ ... + tpM)+(fp1 + fp2+ ... + fpM)+(fn1 + fn2+ ... + fnM))
 That is the same for other metrics too.
 Cloud-Net+ code will be available soon.

**Comment by Silengcewang** [comment]
Hello.
Sorry to disturb you again.But I really can't understand why the evaluation metrics of the same network can improve so much in your three papers:FCN、Cloud-net and Cloude-net++.If you use the same code wirted by matlab or use some special tricks. 

Really,thank you for your reply!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SorourMo/38-Cloud-A-Cloud-Segmentation-Dataset"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月30日(星期一) 凌晨0:02
收件人:&nbsp;"SorourMo/38-Cloud-A-Cloud-Segmentation-Dataset"<38-Cloud-A-Cloud-Segmentation-Dataset@noreply.github.com&gt;;
抄送:&nbsp;"鼬手边是佐手"<799510953@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SorourMo/38-Cloud-A-Cloud-Segmentation-Dataset] Why  are the two evaluation indicators very different (#7)





 
Hi.
 The evaluation metrics described in Cloud-net are calculated first over each test image. Then they are averaged over the total number of test images. Like this:
 Jaccard of the first test image: Jaccard1 = tp1/(tp1+fp1+fn1)
 Jaccard of the second test image: Jaccard2 = tp2/(tp2+fp2+fn2)
 .
 .
 Total Jaccard = (Jaccard1+Jaccard2+...)/M
 where M is the total num of images.
 In Cloud-net+, tp, fp, fn, and tn are measured for each target class and then metrics are calculated as mentioned in the "evaluation metrics" section of the paper. Like this:
 Total Jaccard = (tp1 + tp2+ ... + tpM)/((tp1 + tp2+ ... + tpM)+(fp1 + fp2+ ... + fpM)+(fn1 + fn2+ ... + fnM))
 That is the same for other metrics too.
 Cloud-Net+ code will be available soon.

**Comment by SorourMo** [comment]
There is no trick. The Matlab code provided [here](https://github.com/SorourMo/38-Cloud-A-Cloud-Segmentation-Dataset/tree/master/evaluation) are **only** for the FCN and Cloud-Net papers. As I said before (here and in the papers), this code calculates metrics for each image and then averages those metrics over 20 scenes of 38-Cloud test set.

However, if you want to calculate metrics over each class, and not each image, (same as what've done in Cloud-Net+ paper), you need to write your own code to do so.
